//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mesajlasmaPlatformu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kayit
    {
        public string kayitId { get; set; }
        public string kayitGrupId { get; set; }
        public string kayitKisiId { get; set; }
        public string kayitMesajId { get; set; }
    
        public virtual Gruplar Gruplar { get; set; }
        public virtual Kisiler Kisiler { get; set; }
        public virtual Mesajlar Mesajlar { get; set; }
    }
}
