//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mesajlasmaPlatformu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesajlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mesajlar()
        {
            this.Kayit = new HashSet<Kayit>();
        }
    
        public string mesajId { get; set; }
        public string mesajText { get; set; }
        public string kimdenId { get; set; }
        public string kimeId { get; set; }
        public string grupId { get; set; }
        public int bulkMesaj { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kayit> Kayit { get; set; }
        public virtual Kisiler Kisiler { get; set; }
    }
}
